### ISSUE TITLE
Android shooting video error

### ISSUE THREAD

**Issue by caoruonan** [react-native-community/react-native-image-picker#1076]
When I just opened the app, the Android phone will flash back and report an error.
` java.lang.NullPointerException
        at android.app.ActivityManagerProxy.grantUriPermission(ActivityManagerNative.java:3481)
        at android.app.ContextImpl.grantUriPermission(ContextImpl.java:1748)
        at android.content.ContextWrapper.grantUriPermission(ContextWrapper.java:577)
        at android.content.ContextWrapper.grantUriPermission(ContextWrapper.java:577)
        at com.imagepicker.ImagePickerModule.launchCamera(ImagePickerModule.java:288)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
        at android.os.Looper.loop(Looper.java:136)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
        at java.lang.Thread.run(Thread.java:841)`

But when I first open the camera to take a photo, and then video recording, it will work normally. Has anyone encountered the same problem?

**Comment by caoruonan** [comment]
for Android 4.4
