### ISSUE TITLE
Video Select Crash on Android Q (29.x)

### ISSUE THREAD

**Issue by aniciom** [react-native-community/react-native-image-picker#1139]
# Bug

When i choose a video from my android's q emulator library,  the application crashes with the following error:

`   java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=13003, result=-1, data=Intent { dat=content://com.google.android.apps.photos.contentprovider/-1/2/content://media/external/video/media/25/ORIGINAL/NONE/1436256159 flg=0x1 clip={text/uri-list U:content://com.google.android.apps.photos.contentprovider/-1/2/content%3A%2F%2Fmedia%2Fexternal%2Fvideo%2Fmedia%2F25/ORIGINAL/NONE/1436256159} }} to activity {com.rndchat060/com.rndchat060.MainActivity}: java.lang.IllegalArgumentException: Invalid column latitude
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4843)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4884)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7343)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:933)
     Caused by: java.lang.IllegalArgumentException: Invalid column latitude
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
        at android.content.ContentResolver.query(ContentResolver.java:944)
        at android.content.ContentResolver.query(ContentResolver.java:880)
        at android.content.ContentResolver.query(ContentResolver.java:836)
        at com.imagepicker.utils.RealPathUtil.getDataColumn(RealPathUtil.java:131)
        at com.imagepicker.utils.RealPathUtil.getRealPathFromURI(RealPathUtil.java:101)
        at com.imagepicker.ImagePickerModule.getRealPathFromURI(ImagePickerModule.java:635)
        at com.imagepicker.ImagePickerModule.onActivityResult(ImagePickerModule.java:413)
        at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:277)
        at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:704)
        at com.reactnativenavigation.react.ReactGateway.onActivityResult(ReactGateway.java:76)
        at com.reactnativenavigation.NavigationActivity.onActivityResult(NavigationActivity.java:83)
        at android.app.Activity.dispatchActivityResult(Activity.java:8110)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4836)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4884) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7343) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:933) `

Seems its not able to get the metadata from the file, its not happening in earlier versions, maybe its an emulator problem? I couldn't test it on a real device using android q, because i haven't one, maybe in a real device its not happening, anyways i need to record some video files and be able to open them to do some tests.

Its working fine with photos.

Thanks

## Environment info

React native info output:

```System:
    OS: macOS 10.14.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz
    Memory: 140.86 MB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 10.16.0 - ~/.nvm/versions/node/v10.16.0/bin/node
    Yarn: 1.16.0 - ~/.nvm/versions/node/v10.16.0/bin/yarn
    npm: 6.10.2 - ~/.nvm/versions/node/v10.16.0/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.4, macOS 10.14, tvOS 12.4, watchOS 5.3
    Android SDK:
      API Levels: 25, 26, 27, 28, 29
      Build Tools: 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.0, 28.0.2, 28.0.3, 29.0.1
      System Images: android-25 | Google APIs Intel x86 Atom_64, android-26 | Google APIs Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom_64, android-29 | Google APIs Intel x86 Atom_64
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 10.3/10G8 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.4 => 0.60.4 
```

Library version: 1.0.1

## Steps To Reproduce

1. Open the App
2. Run the follow code

```
const imagePickerOptions = {
            takePhotoButtonTitle: null,
            title: 'Upload Media',
            chooseFromLibraryButtonTitle: 'Choose From Library',
            mediaType: 'video',
          }
      
          ImagePicker.showImagePicker(imagePickerOptions, (response) => {
               console.log(response);
});
```
3. When you select the video you'll see in the logcat, the exception pasted above

Describe what you expected to happen:

1. No crash expected

**Comment by kishanmundha** [comment]
I'm also getting same error for android 10. Any progress ?

**Comment by amadeu01** [comment]
I'm having the same problem with Android 10. Real devices and simulators.

**Comment by aniciom** [comment]
none taking care of this issue?

**Comment by aniciom** [comment]
Any news about this matter?

Thanks

**Comment by eramudeep** [comment]
i also getting crash on video select

**Comment by amadeu01** [comment]
Check if that fix work for you folkd #1202

**Comment by Josin22** [comment]
same to me, android 9, oppo

**Comment by whitesnow9291** [comment]
Is there any solution for this?

**Comment by hiepnm** [comment]
same error

**Comment by martrik** [comment]
Same error using version `2.3.1` of the library.

**Comment by eduardosmartcare** [comment]
Is there any solution for this?

**Comment by Johan-dutoit** [comment]
Try  3.x.x.  If the issue still exists, create a new issue.  2.x.x. is not longer being supported.
