### ISSUE TITLE
Exception on Android

### ISSUE THREAD

**Issue by avoloshko** [react-native-community/react-native-image-picker#1182]
09-24 01:13:46.236  9820  9820 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: quality must be 0..100
09-24 01:13:46.236  9820  9820 E AndroidRuntime: 	at android.graphics.Bitmap.compress(Bitmap.java:1626)
09-24 01:13:46.236  9820  9820 E AndroidRuntime: 	at com.imagepicker.utils.MediaUtils.getResizedImage(MediaUtils.java:157)
09-24 01:13:46.236  9820  9820 E AndroidRuntime: 	at com.imagepicker.ImagePickerModule.onActivityResult(ImagePickerModule.java:477)
09-24 01:13:46.236  9820  9820 E AndroidRuntime: 	at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:277)
09-24 01:13:46.236  9820  9820 E AndroidRuntime: 	at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:704)
09-24 01:13:46.236  9820  9820 E AndroidRuntime: 	at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:129)
09-24 01:13:46.236  9820  9820 E AndroidRuntime: 	at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:75)
09-24 01:13:46.236  9820  9820 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:7758)
09-24 01:13:46.236  9820  9820 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4577)
09-24 01:13:46.236  9820  9820 E AndroidRuntime: 	... 11 more
09-24 01:13:46.239  1474  2133 D Debug   : !@DumpState : SHIP

## Environment info

React native info output:

```bash
 // paste it here
```

Library version: x.x.x

## Steps To Reproduce

const options = {
    mediaType: 'photo',
    quality: 50,
  };

1.
2.
...

Describe what you expected to happen:

1.
2.

**Comment by avoloshko** [comment]
I think the main reason is that for some reason the code doesn't use options.quality, but instead it uses

result.quality

```
scaledPhoto = Bitmap.createBitmap(photo, 0, 0, photo.getWidth(), photo.getHeight(), matrix, true);
        ByteArrayOutputStream bytes = new ByteArrayOutputStream();
        scaledPhoto.compress(Bitmap.CompressFormat.JPEG, result.quality, bytes);
```
