### ISSUE TITLE
App completly crashes on multiple one image picking

### ISSUE THREAD

**Issue by wojcikiewiczm** [react-native-community/react-native-image-picker#1183]
# Bug

Hi my app is crashing when I open and pick image multiple times in a row (it's random but it's between 4 and 7 times) on Android (API 25). Picker is opened from react-native's Modal component.

```
2019-09-24 11:38:05.787 1627-1627/com.fixummobileapp E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 543424)
2019-09-24 11:38:06.228 1627-1627/com.fixummobileapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.fixummobileapp, PID: 1627
    java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 543424 bytes
        at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:160)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6986)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
     Caused by: android.os.TransactionTooLargeException: data parcel size 543424 bytes
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:1142)
        at android.app.IActivityManager$Stub$Proxy.activityStopped(IActivityManager.java:3890)
        at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:144)
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:6986) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```

## Environment info

Windows 10
React native 0.60.0
react-native-image-picker: 1.1.0

 buildToolsVersion = "28.0.3"
 minSdkVersion = 16
 compileSdkVersion = 28
 targetSdkVersion = 28
 supportLibVersion = "28.0.0"

## Steps To Reproduce

I just open and pick one image multiple times in a row (4-7 times).

## Reproducible sample code
```
     ImagePicker.launchImageLibrary(options, (response) => {
       if (response.uri) {
         addPhoto({value: Platform.OS === 'ios' ? response.origURL : response.uri, key: photoType}); // redux action
        closeModal(); // closes reeact-native modal
      }
     });
```

**Comment by Prat1143** [comment]
Facing the same issue - java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 541732 bytes.

Any solution?

**Comment by Prat1143** [comment]
> ava.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 541732 bytes.

@wojcikiewiczm did you find any solution?
