### ISSUE TITLE
Android: App restart on come back from take photo 

### ISSUE THREAD

**Issue by tunm1228** [react-native-community/react-native-image-picker#1185]
# Bug

## Environment info

React native info output:

```bash
 // paste it here
```

Library version: x.x.x

## Steps To Reproduce

1.
2.
...

Describe what you expected to happen:

1.
2.

**Comment by nemanjam** [comment]
I have the same issue on Android 5.0.1 on real device. In emulator it works fine. When you select the photo and get back to app it reloads with no errors.

Here is the relevant logcat from Android studio:

```
10-03 01:04:05.361 19142-19142/? W/System.err: java.lang.ClassNotFoundException: com.facebook.flipper.ReactNativeFlipper
10-03 01:04:05.371 19142-19152/? W/art: Suspending all threads took: 10.499ms
10-03 01:04:05.371 19142-19142/? W/System.err:     at java.lang.Class.classForName(Native Method)
10-03 01:04:05.371 19142-19142/? W/System.err:     at java.lang.Class.forName(Class.java:308)
10-03 01:04:05.371 19142-19142/? W/System.err:     at java.lang.Class.forName(Class.java:272)
10-03 01:04:05.371 19142-19142/? W/System.err:     at com.imageupload.MainApplication.initializeFlipper(MainApplication.java:63)
10-03 01:04:05.371 19142-19142/? W/System.err:     at com.imageupload.MainApplication.onCreate(MainApplication.java:48)
10-03 01:04:05.371 19142-19142/? W/System.err:     at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1011)
10-03 01:04:05.371 19142-19142/? W/System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4657)
10-03 01:04:05.371 19142-19142/? W/System.err:     at android.app.ActivityThread.access$1500(ActivityThread.java:155)
10-03 01:04:05.371 19142-19142/? W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1384)
10-03 01:04:05.371 19142-19142/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
10-03 01:04:05.371 19142-19142/? W/System.err:     at android.os.Looper.loop(Looper.java:135)
10-03 01:04:05.371 19142-19142/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5376)
10-03 01:04:05.371 19142-19142/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
10-03 01:04:05.371 19142-19142/? W/System.err:     at java.lang.reflect.Method.invoke(Method.java:372)
10-03 01:04:05.371 19142-19142/? W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:908)
10-03 01:04:05.371 19142-19142/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:703)
10-03 01:04:05.371 19142-19142/? W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.facebook.flipper.ReactNativeFlipper" on path: DexPathList[[zip file "/data/app/com.imageupload-1/base.apk"],nativeLibraryDirectories=[/data/app/com.imageupload-1/lib/arm, /vendor/lib, /system/lib]]
10-03 01:04:05.371 19142-19142/? W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
10-03 01:04:05.371 19142-19142/? W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
10-03 01:04:05.371 19142-19142/? W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
10-03 01:04:05.371 19142-19142/? W/System.err: 	... 16 more
10-03 01:04:05.371 19142-19142/? W/System.err: 	Suppressed: java.lang.ClassNotFoundException: com.facebook.flipper.ReactNativeFlipper
10-03 01:04:05.371 19142-19142/? W/System.err:     at java.lang.Class.classForName(Native Method)
10-03 01:04:05.371 19142-19142/? W/System.err:     at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
10-03 01:04:05.371 19142-19142/? W/System.err:     at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
10-03 01:04:05.371 19142-19142/? W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
10-03 01:04:05.371 19142-19142/? W/System.err: 		... 17 more
10-03 01:04:05.371 19142-19142/? W/System.err: 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
10-03 01:04:05.541 19142-19142/? W/art: Before Android 4.1, method android.graphics.PorterDuffColorFilter androidx.vectordrawable.graphics.drawable.VectorDrawableCompat.updateTintFilter(android.graphics.PorterDuffColorFilter, android.content.res.ColorStateList, android.graphics.PorterDuff$Mode) would have incorrectly overridden the package-private method in android.graphics.drawable.Drawable
10-03 01:04:05.831 19142-19176/? W/unknown:InspectorPackagerConnection: Couldn't connect to packager, will silently retry
10-03 01:04:05.921 19142-19142/? W/unknown:ReactNative: Packager connection already open, nooping.
10-03 01:04:06.131 19142-19142/? E/MediaProfilesEx-JNI: register_com_lge_media_MediaProfilesEx
10-03 01:04:06.131 19142-19142/? E/MediaRecorderEx-JNI: register_com_lge_media_MediaRecorderEx
10-03 01:04:06.131 19142-19142/? E/SurfaceControlEx: register_com_lge_view_SurfaceControlEx
10-03 01:04:06.141 19142-19142/? E/MediaPlayerEx-jni: register_com_lge_view_MediaPlayerEx
10-03 01:04:16.121 19142-19142/com.imageupload W/unknown:ReactNative: Packager connection already open, nooping.
10-03 01:04:16.261 19142-19310/com.imageupload W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTGroupViewManager
10-03 01:04:16.261 19142-19310/com.imageupload W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTGroupShadowNode
10-03 01:04:16.271 19142-19310/com.imageupload W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTShapeViewManager
10-03 01:04:16.271 19142-19310/com.imageupload W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTShapeShadowNode
10-03 01:04:16.281 19142-19310/com.imageupload W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTTextViewManager
10-03 01:04:16.281 19142-19310/com.imageupload W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTTextShadowNode
10-03 01:04:16.281 19142-19310/com.imageupload W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.checkbox.ReactCheckBoxManager
10-03 01:04:16.321 19142-19310/com.imageupload W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.uimanager.LayoutShadowNode
10-03 01:04:16.341 19142-19310/com.imageupload W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDialogPickerManager
10-03 01:04:16.381 19142-19310/com.imageupload W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.drawer.ReactDrawerLayoutManager
10-03 01:04:16.441 19142-19310/com.imageupload W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.picker.ReactDropdownPickerManager
10-03 01:04:16.451 19142-19310/com.imageupload W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollViewManager
10-03 01:04:16.481 19142-19310/com.imageupload W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactHorizontalScrollContainerViewManager
10-03 01:04:16.491 19142-19310/com.imageupload W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ReactProgressBarViewManager
10-03 01:04:16.501 19142-19310/com.imageupload W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.progressbar.ProgressBarShadowNode
10-03 01:04:16.521 19142-19310/com.imageupload W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.scroll.ReactScrollViewManager
10-03 01:04:16.541 19142-19310/com.imageupload W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager
10-03 01:04:16.551 19142-19310/com.imageupload W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.slider.ReactSliderManager$ReactSliderShadowNode
10-03 01:04:16.551 19142-19310/com.imageupload W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager
10-03 01:04:16.571 19142-19310/com.imageupload W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.switchview.ReactSwitchManager$ReactSwitchShadowNode
10-03 01:04:16.581 19142-19310/com.imageupload W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.swiperefresh.SwipeRefreshLayoutManager
10-03 01:04:16.611 19142-19310/com.imageupload W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewManager
10-03 01:04:16.621 19142-19310/com.imageupload W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.art.ARTSurfaceViewShadowNode
10-03 01:04:16.621 19142-19310/com.imageupload W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageViewManager
10-03 01:04:16.621 19142-19310/com.imageupload W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.frescosupport.FrescoBasedReactTextInlineImageShadowNode
10-03 01:04:16.631 19142-19310/com.imageupload W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.image.ReactImageManager
10-03 01:04:16.651 19142-19310/com.imageupload W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ReactModalHostManager
10-03 01:04:16.661 19142-19310/com.imageupload W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.modal.ModalHostShadowNode
10-03 01:04:16.661 19142-19310/com.imageupload W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactRawTextManager
10-03 01:04:16.671 19142-19310/com.imageupload W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactRawTextShadowNode
10-03 01:04:16.671 19142-19310/com.imageupload W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputManager
10-03 01:04:16.691 19142-19310/com.imageupload W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.textinput.ReactTextInputShadowNode
10-03 01:04:16.701 19142-19310/com.imageupload W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextViewManager
10-03 01:04:16.711 19142-19310/com.imageupload W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactTextShadowNode
10-03 01:04:16.711 19142-19310/com.imageupload W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.view.ReactViewManager
10-03 01:04:16.731 19142-19310/com.imageupload W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.viewpager.ReactViewPagerManager
10-03 01:04:16.751 19142-19310/com.imageupload W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextViewManager
10-03 01:04:16.761 19142-19310/com.imageupload W/unknown:ViewManagerPropertyUpdater: Could not find generated setter for class com.facebook.react.views.text.ReactVirtualTextShadowNode
10-03 01:04:18.271 19142-19310/com.imageupload W/art: Attempt to remove local handle scope entry from IRT, ignoring
```

**Comment by hardibhalodiya** [comment]
I have the same issue on Android 8.0.0 on real device.When I select the photo and get back to app it reloads with no errors. Please give some solution.

**Comment by amadeu01** [comment]
Same here

**Comment by arundev-kv** [comment]
Same here on Android 6

**Comment by vuhoangha** [comment]
I have same issue :(((

**Comment by tautvilas** [comment]
Probably duplicate with #1232

**Comment by arifinoid** [comment]
same here, happens on android low device

**Comment by moh3n9595** [comment]
same issue
