### ISSUE TITLE
[Android] Picking unsupported file type crashes app

### ISSUE THREAD

**Issue by Frank1234** [react-native-community/react-native-image-picker#1196]
# Bug
When resizing is enabled, on Android, picking an image file with mime type `image/tiff` in the ImagePicker might crash the app. Same for a file with mime type `image/heic`.

## Steps to reproduce
- Download any TIFF or HEIC file, put it on your device.
- Open the image picker, with resize options, like:
`{
				quality: 0.9,
				maxWidth: 1024,
				maxHeight: 1024,
				noData: true,
				mediaType: 'photo'
			}`
- Pick the TIFF or HEIC file
- App crashes on some of the TIFF and HEIC files.

## Environment info
Android only

## Expected result
Best option: Not showing this image type in the picker.

Quick fix: At least give a proper error back, instead of crashing the app. For this, a nullcheck is needed, see stacktrace.

## StackTrace
```Caused by: java.lang.NullPointerException: Attempt to read from field 'java.io.File com.imagepicker.media.ImageConfig.resized' on a null object reference
        at com.imagepicker.ImagePickerModule.onActivityResult(ImagePickerModule.java:478)
        at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:277)
        at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:704)
        at com.reactnativenavigation.react.ReactGateway.onActivityResult(ReactGateway.java:76)
        at com.reactnativenavigation.NavigationActivity.onActivityResult(NavigationActivity.java:88)
        at android.app.Activity.dispatchActivityResult(Activity.java:7276)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4264)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4312) 
        at android.app.ActivityThread.-wrap19(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1644) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) ```

**Comment by pandya293** [comment]
facing same error while choose .mp4 video using launchImageLibrary method
received response {"errorCode": "others", "errorMessage": "Unsupported file type"}

**Comment by afilp** [comment]
I have similar problems with the HEIC format. Is there a solution to this? Thanks!

**Comment by pandya293** [comment]
You need to send 'mixed' instead of 'photo'. All type are working in mixed.

**Comment by afilp** [comment]
@pandya293 I have a requirement that only 'photos' need to be browsed/selected not 'videos', when the picker opens. If I put 'mixed' it like saying to the users that they could also choose a `video` in a field where it expects a photo. How can we cope with that?

**Comment by pandya293** [comment]
This is a bug, need to be fixed by the development team of
react-native-image-picker.
I have given you temporary solution for this error.

**Comment by afilp** [comment]
@pandya293 Thanks, I understand.

This issue is `closed` though, do they have it documented somewhere else as a bug?

**Comment by JiaBao98** [comment]
i face issue when select video also (when options selectionLimit:0) ,which means i can select 1 or more number of video when selectionLimit:0 ,but I just select 1 video only .Then it return me response {"errorCode": "others", "errorMessage": "Unsupported file type"}
BUT, if I just select 1 video from "Recent Files in App" of emulator , then it will no had any issue
Any idea to fix this issue? Thanks for help

**Comment by JiaBao98** [comment]
> i face issue when select video also (when options selectionLimit:0) ,which means i can select 1 or more number of video when selectionLimit:0 ,but I just select 1 video only .Then it return me response {"errorCode": "others", "errorMessage": "Unsupported file type"} BUT, if I just select 1 video from "Recent Files in App" of emulator , then it will no had any issue Any idea to fix this issue? Thanks for help

I select multiple images is work fine ,and my options is like below:
const options: any = {
      storageOptions: {
        path: 'images'
        // durationLimit: 10
      },
      selectionLimit: 0,
      mediaType: 'mixed'
    };
