### ISSUE TITLE
After updating to RN 0.61 camera won't launch

### ISSUE THREAD

**Issue by ospfranco** [react-native-community/react-native-image-picker#1211]
# Bug

It seems on the latest implementation some image attempts to be loaded only for the camera package to fail and the camera not being launched at all, looking into the logcat errors I see the following error:

```
10-31 11:21:47.460 25897 26064 W System.err: java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/emulated/0/Pictures/capmofiles/image-190ef1ea-5720-42dc-a05a-e2fe37397492.jpg
10-31 11:21:47.460 25897 26064 W System.err: 	at androidx.core.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:739)
10-31 11:21:47.460 25897 26064 W System.err: 	at androidx.core.content.FileProvider.getUriForFile(FileProvider.java:418)
10-31 11:21:47.460 25897 26064 W System.err: 	at com.imagepicker.utils.RealPathUtil.compatUriFromFile(RealPathUtil.java:30)
10-31 11:21:47.460 25897 26064 W System.err: 	at com.imagepicker.ImagePickerModule.launchCamera(ImagePickerModule.java:274)
10-31 11:21:47.460 25897 26064 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
10-31 11:21:47.461 25897 26064 W System.err: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:371)
10-31 11:21:47.461 25897 26064 W System.err: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:150)
10-31 11:21:47.461 25897 26064 W System.err: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
10-31 11:21:47.461 25897 26064 W System.err: 	at android.os.Handler.handleCallback(Handler.java:873)
10-31 11:21:47.461 25897 26064 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-31 11:21:47.461 25897 26064 W System.err: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:26)
10-31 11:21:47.461 25897 26064 W System.err: 	at android.os.Looper.loop(Looper.java:210)
10-31 11:21:47.461 25897 26064 W System.err: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:225)
10-31 11:21:47.461 25897 26064 W System.err: 	at java.lang.Thread.run(Thread.java:764)

```

## Environment info
"react-native-image-picker": "^1.1.0",
"react-native": "0.61.2",

React native info output:
System:
    OS: macOS 10.15.1
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 457.71 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.10.0 - ~/.volta/tools/image/node/12.10.0/6.10.3/bin/node
    Yarn: 1.19.1 - ~/.volta/tools/image/yarn/1.19.1/bin/yarn
    npm: 6.10.3 - ~/.volta/tools/image/node/12.10.0/6.10.3/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.1, DriverKit 19.0, macOS 10.15, tvOS 13.0, watchOS 6.0
    Android SDK:
      API Levels: 27, 28, 29
      Build Tools: 27.0.3, 28.0.3, 29.0.0
      System Images: android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 11.1/11A1027 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.2 => 0.61.2

## Steps To Reproduce
I'm sorry I won't be able to produce a working sample, this seems to be related to the way we saved images?

**Comment by ospfranco** [comment]
Sorry my bad, on RN 0.61 it is now necessary to configure a file provider, I missconfigured it:

file os somewhere around here:
android/app/main/res/xml/filepaths.xml

Original:
```
<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
  <external-path name="myexternalimages" path="Download/" />
</paths>
```

Fixed:
```
<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
  <external-path name="cache_dir" path="/" />
</paths>
```
