### ISSUE TITLE
app crash

### ISSUE THREAD

**Issue by issamabdelkrim** [react-native-community/react-native-image-picker#1219]
Hello everyone 
my app crash when i validate picture or video that i record . 
i make adb logcat and it show me this error : 
ReactInstanceManager.ctor() 
can someone plz help me to fix it

**Comment by pawanvivekananda** [comment]
Facing same issue once image is selected app crashes.

**Comment by JosManMx** [comment]
I have a similar issue with the lasts releases; this solved for me:

check the imports; if you have:

`import { showImagePicker } from 'react-native-image-picker';`

changed the import `import RNImagePicker from 'react-native-image-picker';`
and implement in this way: `RNImagePicker.showImagePicker(options, (response) => {})`

**Comment by pawanvivekananda** [comment]
I am using below code with react native version

"react": "16.9.0",
"react-native": "0.61.2",


```
import ImagePicker from 'react-native-image-picker';

// More info on all the options is below in the API Reference... just some common use cases shown here
const options = {
  title: 'Select Avatar',
  customButtons: [{ name: 'fb', title: 'Choose Photo from Facebook' }],
  storageOptions: {
    skipBackup: true,
    path: 'images',
  },
};

/**
 * The first arg is the options object for customization (it can also be null or omitted for default options),
 * The second arg is the callback which sends object: response (more info in the API Reference)
 */
ImagePicker.showImagePicker(options, (response) => {
  console.log('Response = ', response);

  if (response.didCancel) {
    console.log('User cancelled image picker');
  } else if (response.error) {
    console.log('ImagePicker Error: ', response.error);
  } else if (response.customButton) {
    console.log('User tapped custom button: ', response.customButton);
  } else {
    const source = { uri: response.uri };

    // You can also display the image using data:
    // const source = { uri: 'data:image/jpeg;base64,' + response.data };

    this.setState({
      avatarSource: source,
    });
  }
});
```

**Comment by pawanvivekananda** [comment]
App crashes after selecting image and getting response.

**Comment by cinder92** [comment]
@pawanvivekananda did you find any solution?

**Comment by dileepjb2** [comment]
> App crashes after selecting image and getting response.

any solution?

**Comment by NestedLooper** [comment]
Add the missing permissions to your plist file. Info [here](https://github.com/react-native-community/react-native-image-picker/issues/1201#issuecomment-543795795).

**Comment by aemre** [comment]
Any solution ?

**Comment by aemre** [comment]
I think androidx creating this issue any update on that ?

**Comment by arn3342** [comment]
Having this same issue again on an emulator and also on real device. No exceptions thrown.

**Comment by Prat1143** [comment]
Facing the same issue as soon as I select an image to upload the app crashes without giving any errors, but it's displaying the response in the console. I also tried using react-native-image-crop-picker, but it too made the app crash on image upload. I was first running the app using the command "npx react-native run-android". And when the app crashed it was only showing the response of the uploaded image. But then I switched to Android Studio and built the app from there and as soon as I uploaded the image the following error was displayed in the logcat-

{ height: 200,
      width: 92,
      type: 'image/jpeg',
      fileName: 'rn_image_picker_lib_temp_54c4dc23-202f-45a0-94da-1b05f313f8ed.jpg',
      fileSize: 13008,
      uri: 'file:///data/user/0/com.abc/cache/rn_image_picker_lib_temp_54c4dc23-202f-45a0-94da-1b05f313f8ed.jpg' }
2021-03-26 19:44:46.889 7469-7469/com.abc E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.abc, PID: 7469
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=13002, result=-1, data=Intent { dat=content://media/external/images/media/168402 flg=0x1 (has extras) }} to activity {com.abc/com.abc.MainActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.bridge.Callback.invoke(java.lang.Object[])' on a null object reference
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5078)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5120)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199)
        at android.os.Handler.dispatchMessage(Handler.java:112)
        at android.os.Looper.loop(Looper.java:216)
        at android.app.ActivityThread.main(ActivityThread.java:7625)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
     Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.bridge.Callback.invoke(java.lang.Object[])' on a null object reference
        at com.reactlibrary.RNPgReactNativeSdkModule$1.onActivityResult(RNPgReactNativeSdkModule.java:157)
        at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:308)
        at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:758)
        at com.facebook.react.ReactDelegate.onActivityResult(ReactDelegate.java:90)
        at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:112)
        at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:68)
        at android.app.Activity.dispatchActivityResult(Activity.java:7797)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5071)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5120) 
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2199) 
        at android.os.Handler.dispatchMessage(Handler.java:112) 
        at android.os.Looper.loop(Looper.java:216) 
        at android.app.ActivityThread.main(ActivityThread.java:7625) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987) 
2021-03-26 19:44:46.892 7469-7469/com.abc D/e: CrashLogs : {"ts":"2021-03-26 19:44:46","app_id":"UNKNOWN","package":"UNKNOWN","android_id":"UNKNOWN","platform":"Linux","os_version":"28","device_model":"COR-AL00","device_name":"HONOR","sdk_version":"1.6.0","network_type":"UNKNOWN","stack":"com.reactlibrary.RNPgReactNativeSdkModule$1.onActivityResult(RNPgReactNativeSdkModule.java:157)","cause":"java.lang.NullPointerException: Attempt to invoke interface method 'void com.facebook.react.bridge.Callback.invoke(java.lang.Object[])' on a null object reference"}

**Comment by MarianAlexandruAlecu** [comment]
We have the same exact issue:
- empty React Native project
- react-native-image-picker latest

App crashes after selecting an image.

Any updates on this?

**Comment by HidenPlus** [comment]
> Add the missing permissions to your plist file. Info [here](https://github.com/react-native-community/react-native-image-picker/issues/1201#issuecomment-543795795).
> 
> If you are having issues on Android, add to the AndroidManifest.xml:
> 
> ```
> <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
> <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
> <uses-permission android:name="android.permission.CAMERA" />
> <uses-feature android:name="android.hardware.camera" />
> <uses-feature android:name="android.hardware.camera.autofocus" />
> ```

This works for me

**Comment by geza909** [comment]
try this solution :
https://lifesaver.codes/answer/android-app-crashes-automatically-when-opened-1122

**Comment by Prat1143** [comment]
> try this solution : https://lifesaver.codes/answer/android-app-crashes-automatically-when-opened-1122

The given link is not working. Can you share any other link for the solution or the solution itself please?

**Comment by mattlewer** [comment]
4 years since this was posted, anyone have a solution? Still experiencing this myself...

"react-native-image-picker": "4.10.1",
"react-native": "0.72.1",

**Comment by wagneer-nascimento** [comment]
Add quality: 0.1      includeBase64: true,
 
 and test app replay
 
 const response = await launchImageLibrary({
                mediaType: "photo",
                selectionLimit: 1,
                quality: 0.1,
                includeBase64: true,
            });

**Comment by PauZeA** [comment]
Someone has found any solution?

**Comment by mattlewer** [comment]
> Someone has found any solution?

Not a solution, but what I believe is the cause.

From my attempts to get this to work, this seems to be caused by the library opening the camera as a separate activity, the phones OS then see's that the React Native activity is idle and kills it to manage memory, so when you accept the image and try to get sent back, there is nothing to be sent back to, or it sends you back to refreshed app as if it was freshly opened, due to restarting of the activity (example below). From my experience this doesn't happen on all phones or consistently, which makes it even more annoying as you're at the mercy of the OS.

To prevent an outright crash of the app, change the line in MainActivity.java from:
```
super.onCreate(savedInstanceState);
```
to
```
super.onCreate(null);
```

**Comment by PauZeA** [comment]
> onCreate

I already have this line. 

Specifically what happens is that when the selected file is big (specifically happens with the large videos) the app shows the "not working app" message and asks to wait for it to work or to close it, but right after it appears the launchImageLibrary responds and the message closes itself. However if the message appears after the response, even when you tell it to wait and the app functions correctly, the message keeps showing until you select to close it.
