### ISSUE TITLE
Crash when I pick a video on Android Q!!!

### ISSUE THREAD

**Issue by Josin22** [react-native-community/react-native-image-picker#1221]
# Bug
Crash when I pick a video on Android Q

## Environment info

 OS: macOS Mojave 10.14.6
    CPU: (6) x64 Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz
    Memory: 23.20 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.12.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 16, 23, 24, 25, 26, 27, 28, 29
      Build Tools: 20.0.0, 26.0.0, 27.0.3, 28.0.0, 28.0.3, 29.0.1, 29.0.2
      System Images: android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.5900203
    Xcode: 11.2/11B52 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0
    react-native: 0.61.4 => 0.61.4
  npmGlobalPackages:
    react-native-cli: 2.0.1

Library version: 1.1.0

## Steps To Reproduce
1. pick a video from the library on Android device, then crash

Describe what you expected to happen:

1. no crash when I pick a video

## Reproducible sample code

Process: com.rocketvideo, PID: 19650
    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=13003, result=-1, data=Intent { dat=content://com.google.android.apps.photos.contentprovider/-1/2/content://media/external/video/media/26/ORIGINAL/NONE/1084297323 flg=0x1 clip={text/uri-list U:content://com.google.android.apps.photos.contentprovider/-1/2/content%3A%2F%2Fmedia%2Fexternal%2Fvideo%2Fmedia%2F26/ORIGINAL/NONE/1084297323} }} to activity {com.rocketvideo/com.rocketvideo.MainActivity}: java.lang.IllegalArgumentException: Invalid column latitude
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4845)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4886)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.IllegalArgumentException: Invalid column latitude
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:170)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:140)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:423)
        at android.content.ContentResolver.query(ContentResolver.java:944)
        at android.content.ContentResolver.query(ContentResolver.java:880)
        at android.content.ContentResolver.query(ContentResolver.java:836)
        at com.imagepicker.utils.RealPathUtil.getDataColumn(RealPathUtil.java:131)
        at com.imagepicker.utils.RealPathUtil.getRealPathFromURI(RealPathUtil.java:101)
        at com.imagepicker.ImagePickerModule.getRealPathFromURI(ImagePickerModule.java:659)
        at com.imagepicker.ImagePickerModule.onActivityResult(ImagePickerModule.java:436)
        at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:275)
        at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:703)
        at com.facebook.react.ReactDelegate.onActivityResult(ReactDelegate.java:89)
        at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:110)
        at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:67)
        at android.app.Activity.dispatchActivityResult(Activity.java:8110)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4838)

**Comment by builtbyproxy** [comment]
@Josin22 Can you confirm for me please that this does indeed crash. 
I have a bug in my current app where it appears like the app crashes. By this I mean we click upload photo -> take the photo -> confirm -> 'crash'. 

However, it doesn't actually crash, it just doesn't callback to the application. Almost as though linking/Android's 'Intent' is broken. We have referenced it here: https://github.com/GetStream/stream-chat-react-native/issues/114#issuecomment-574223150

In order to validate you are experiencing the same bug. Run this in your simulator or on your device whilst connected to your computer. Ensure you have Android Studio open at the same time and see what your logcat is displaying: https://developer.android.com/studio/debug/am-logcat

If you aren't getting an actual crash there's a high chance you have the same bug as we do. Thanks @Josin22

**Comment by wulaizi** [comment]
在华为手机上选择相册 能选择到视频，一旦选择视频就闪退
