### ISSUE TITLE
App crashed with this error:Didn't find class "com.imagepicker.FileProvider" on android 5.1

### ISSUE THREAD

**Issue by zahrat** [react-native-community/react-native-image-picker#1277]
I use react-native-image-picker. It's not working on devices with android 5.1 or android 4.3. App crashing on start.  I tested with android 6 , 9,8 , and it's work fine.
here is the logcat of android studio
`01-28 13:48:51.077 2709-2709/com.eadverx.irandokht E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to get provider com.imagepicker.FileProvider: java.lang.ClassNotFoundException: Didn't find class "com.imagepicker.FileProvider" on path: DexPathList[[zip file "/data/app/com.eadverx.irandokht-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.eadverx.irandokht-2, /system/lib]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:4882)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4485)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4425)
        at android.app.ActivityThread.access$1300(ActivityThread.java:141)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:5103)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:525)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.imagepicker.FileProvider" on path: DexPathList[[zip file "/data/app/com.eadverx.irandokht-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.eadverx.irandokht-2, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:53)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
        at android.app.ActivityThread.installProvider(ActivityThread.java:4867)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4485) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4425) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:141) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:137) 
        at android.app.ActivityThread.main(ActivityThread.java:5103) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:525) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
        at dalvik.system.NativeStart.main(Native Method) `

my package.json is :
`{
  "name": "Irandokht",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.7.1",
    "@react-native-community/geolocation": "^2.0.2",
    "@react-native-community/netinfo": "^4.6.1",
    "@react-native-community/viewpager": "^3.3.0",
    "create-react-class": "^15.6.3",
    "moment-jalaali": "^0.9.1",
    "native-base": "^2.13.8",
    "prop-types": "^15.7.2",
    "react": "16.9.0",
    "react-advance-jalaali-datepicker": "^1.2.2",
    "react-native": "0.61.4",
    "react-native-android-location-services-dialog-box": "^2.8.2",
    "react-native-best-viewpager": "^1.0.1",
    "react-native-dialog": "^5.6.0",
    "react-native-elements": "^1.2.7",
    "react-native-gesture-handler": "^1.5.2",
    "react-native-image-pan-zoom": "^2.1.11",
    "react-native-image-picker": "^2.2.1",
    "react-native-ionicons": "^4.6.3",
    "react-native-jalali-date-picker-rtl": "^1.0.1",
    "react-native-maps": "0.26.1",
    "react-native-material-dropdown": "^0.11.1",
    "react-native-modals": "^0.19.9",
    "react-native-netinfo": "^1.1.0",
    "react-native-persian-calendar-picker": "^3.1.1",
    "react-native-picker": "^4.3.7",
    "react-native-picker-select": "^6.3.3",
    "react-native-ratings": "^6.5.0",
    "react-native-reanimated": "^1.4.0",
    "react-native-responsive-screen": "^1.3.0",
    "react-native-screens": "1.0.0-alpha.23",
    "react-native-simple-toast": "^1.0.0",
    "react-native-slideshow": "^1.0.1",
    "react-native-stars": "^1.1.6",
    "react-native-video": "^5.0.2",
    "react-native-webview": "^7.5.2",
    "react-navigation": "^4.0.10",
    "react-navigation-drawer": "^2.3.3",
    "react-navigation-stack": "^1.10.3",
    "react-navigation-tabs": "^2.6.2",
    "react-redux": "^7.1.3",
    "redux": "^4.0.4",
    "rn-persian-date-picker": "^1.0.6",
    "rn-splash-screen": "^5.2.0"
  },
  "devDependencies": {
    "@babel/core": "^7.7.2",
    "@babel/runtime": "^7.7.2",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.6.0",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.57.0",
    "react-test-renderer": "16.9.0"
  },
  "jest": {
    "preset": "react-native"
  },
  "rnpm": {
    "assets": [
      "./assets/fonts"
    ]
  }
}
`

**Comment by avoloshko** [comment]
Any progress with that? it can be easily reproduced on API-19 emulators.

**Comment by R4DIC4L** [comment]
I see the same issue on a Samsung Galaxy Tab 3 LTE (SM-T111) with android 4.2.2.
This makes the app crash on this device from the beginning, even though I don't use the package on the first screen.

`react-native-image-picker@2.3.4`

See below stack trace from Logcat:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to get provider com.imagepicker.FileProvider: java.lang.ClassNotFoundException: Didn't find class "com.imagepicker.FileProvider"
        at android.app.ActivityThread.installProvider(ActivityThread.java:5070)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4679)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4592)
        at android.app.ActivityThread.access$1400(ActivityThread.java:158)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:5365)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
        at dalvik.system.NativeStart.main(Native Method)
    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.imagepicker.FileProvider"
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:65)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
        at android.app.ActivityThread.installProvider(ActivityThread.java:5055)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4679) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4592) 
        at android.app.ActivityThread.access$1400(ActivityThread.java:158) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1356) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:176) 
        at android.app.ActivityThread.main(ActivityThread.java:5365) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:511) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869) 
        at dalvik.system.NativeStart.main(Native Method) 
```

I already have these gradle.properties, as mentioned here: https://github.com/react-native-image-picker/react-native-image-picker/issues/1088#issuecomment-509755692.
```
android.useAndroidX=true
android.enableJetifier=true
```
