### ISSUE TITLE
NullPointerException when I use bitmap.compress

### ISSUE THREAD

**Issue by bogu5407** [react-native-community/react-native-image-picker#574]
I wanna convert File to bitmap and then bitmap to byte[]. When I debug, file is created and bitmap, too. also it can be converted to byte. But in while(), there is nullpointerException error on bitmap.compress, and it is same when I emulate it.  I don't know why at first or second iteration, it is okay, but after that it isn't.

This is error code.
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.compress(android.graphics.Bitmap$CompressFormat, int, java.io.OutputStream)' on a null object reference
                                                                               at pearsistent.knutreasurehunt.CreatePDF$2.onDataChange(CreatePDF.java:174)
                                                                               at com.google.android.gms.internal.zzbpx.zza(Unknown Source)
                                                                               at com.google.android.gms.internal.zzbqx.zzZT(Unknown Source)
                                                                               at com.google.android.gms.internal.zzbra$1.run(Unknown Source)
                                                                               at android.os.Handler.handleCallback(Handler.java:751)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                               at android.os.Looper.loop(Looper.java:154)
                                                                               at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                               at java.lang.reflect.Method.invoke(Native Method)
                                                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                                                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

/////////////////////////////////////////////////////

It it my code.
///////////////////////////////////////////
    @Override
    public void onCreate(Bundle savedInstanceState) {
                super.onCreate(savedInstanceState);
                setContentView(R.layout.activity_createpdf);

                mDatabase = FirebaseDatabase.getInstance().getReferenceFromUrl("https://treasurehunt-5d55f.firebaseio.com/");
                storage = FirebaseStorage.getInstance();
                storageRef = storage.getReferenceFromUrl("gs://treasurehunt-5d55f.appspot.com");
                fileList = new ArrayList<File>();
                outputStreamArrayList = new ArrayList<>();

                // Read from the database
                mDatabase.child("Team").addValueEventListener(new ValueEventListener() {
                    @Override
                    public void onDataChange(DataSnapshot dataSnapshot) {
                        ///팀을 받아와야 한다..

                        Log.d("DB", "Cheer up ");

                for (DataSnapshot teamSnapshot : dataSnapshot.getChildren()) {
                    Team currentTeam = teamSnapshot.getValue(Team.class);

                    createPDFPath(teamNum);
                    makePDF(currentTeam, teamNum);

                    uploadPDFFile(currentTeam.getTeamName(), teamNum);

                    teamNum++;
                }

            }

            @Override
            public void onCancelled(DatabaseError error) {
                // Failed to read value
                Log.w("DB", "Failed to read value.", error.toException());
            }
        });

    }

///////////////////////////////////////////
  public void makePDF(final Team currentTeam, final int i) {

        mDatabase.child("Team").child(currentTeam.getTeamName()).child("itemList").addValueEventListener(new ValueEventListener() {
            @Override
            public void onDataChange(DataSnapshot dataSnapshot) {
                itemList = new ArrayList<>();
                for (DataSnapshot itemSnapshot : dataSnapshot.getChildren()) {
                    Item currentItem = itemSnapshot.getValue(Item.class);
                    currentItem.setImageReference(findImageFile(currentItem.getName() + ".jpg", currentTeam.getTeamName()));
                    itemList.add(currentItem);
                    Log.d("currnetItem", "" + currentItem.getName());
                }
                Document document = new Document();
                try {
                    document.open();
                    //Step 2
                    PdfWriter.getInstance(document, outputStreamArrayList.get(i));
                    //Step 3
                    document.open();
                    //Step 4 add data to document
                    /////////////for Team
                    PdfPTable table = new PdfPTable(1);
                    //Convert int to string
                    StringBuilder sb = new StringBuilder();
                    sb.append("");
                    sb.append(currentTeam.getTeamPoint());
                    String point = sb.toString();

                    table.addCell(currentTeam.getTeamName());
                    table.addCell("score : " + point);

                    //////////////for Item
                    ArrayList<File> FileList = new ArrayList<File>();

                    for (int item_count = 0; item_count < itemList.size(); item_count++) {
                         File tempfile = getFile(item_count);
                         FileList.add(tempfile);

                        StorageReference islandRef = storageRef.child(currentTeam.getTeamName() + "/" + itemList.get(item_count).getName() + ".jpg");

                        islandRef.getFile(FileList.get(item_count)).addOnSuccessListener(new OnSuccessListener<FileDownloadTask.TaskSnapshot>() {
                            @Override
                            public void onSuccess(FileDownloadTask.TaskSnapshot taskSnapshot) {
                                Log.d("makeFile", "Success");
                                // Local temp file has been created
                            }
                        }).addOnFailureListener(new OnFailureListener() {
                            @Override
                            public void onFailure(@NonNull Exception exception) {
                                // Handle any errors
                                Log.d("makeFile", "Failure");
                            }
                       });
                        //

                        while(count<FileList.size()) {
                            String path = FileList.get(count).getPath();
                            Log.d("FilePath", "" + path);
                            Bitmap bitmap = decodeBase64(path);
                            ByteArrayOutputStream stream = new ByteArrayOutputStream();
                            streamList.add(stream);

                            bitmap.compress(Bitmap.CompressFormat.JPEG, 100, streamList.get(count));
                            byte[] byteArray = streamList.get(count).toByteArray();
                            bitmap.recycle();
                            try {
                                Image image = Image.getInstance(byteArray);
                                table.addCell(image);
                                streamList.get(count).close();
                            } catch (IOException e) {
                                e.printStackTrace();
                            }
                            count++;
                        }

                    }
                    document.add(table);
                    document.close();

                } catch (DocumentException e) {
                    e.printStackTrace();
                }
            }
        }
                @Override
                public void onCancelled (DatabaseError databaseError){

                }
                //You should create pdf in listener

        });
/////////////////////////////////
   public static Bitmap decodeBase64(String input) {
        byte[] decodedByte = Base64.decode(input, 0);
        return BitmapFactory.decodeByteArray(decodedByte, 0,      decodedByte.length);
    }

///////////////////////////////////

I did :
1.      ByteArrayOutputStream stream = new ByteArrayOutputStream() ;  
        $bitmap.compress( CompressFormat.JPEG, 100, stream) ;  
        byte[] byteArray = stream.toByteArray() ;  
        return byteArray ; 

2. I tried to close each stream after using it, but result was same

**Comment by bogu5407** [comment]
I found what is problem. in this code
   for (int item_count = 0; item_count < itemList.size(); item_count++) {
                     File tempfile = getFile(item_count);
                     FileList.add(tempfile);

                    StorageReference islandRef = storageRef.child(currentTeam.getTeamName() + "/" + itemList.get(item_count).getName() + ".jpg");

                    islandRef.getFile(FileList.get(item_count)).addOnSuccessListener(new OnSuccessListener<FileDownloadTask.TaskSnapshot>() {
                        @Override
                        public void onSuccess(FileDownloadTask.TaskSnapshot taskSnapshot) {
                            Log.d("makeFile", "Success");
                            // Local temp file has been created
                        }
                    }).addOnFailureListener(new OnFailureListener() {
                        @Override
                        public void onFailure(@NonNull Exception exception) {
                            // Handle any errors
                            Log.d("makeFile", "Failure");
                        }
                   });
                    //
It can read itemListSize, but it works as only one iteration. Could u tell me reason?
