### ISSUE TITLE
Failure delivering result ResultInfo

### ISSUE THREAD

**Issue by TrustTheBoy** [react-native-community/react-native-image-picker#579]
os : macOS Sierra
d : Samsung Galaxy
```console
  java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=13002, result=-1, data=Intent { dat=content://media/external/images/media/48 flg=0x1 }} to activity {com.mobilecampus/com.mobilecampus.MainActivity}: java.lang.NullPointerException: Attempt to read from field 'java.io.File com.imagepicker.media.ImageConfig.resized' on a null object reference
    at android.app.ActivityThread.deliverResults(ActivityThread.java:3699)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742)
    at android.app.ActivityThread.-wrap16(ActivityThread.java)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:148)
    at android.app.ActivityThread.main(ActivityThread.java:5417)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
    Caused by: java.lang.NullPointerException: Attempt to read from field 'java.io.File com.imagepicker.media.ImageConfig.resized' on a null object reference
    at com.imagepicker.ImagePickerModule.onActivityResult(ImagePickerModule.java:434)
    at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:261)
    at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:659)
    at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:149)
    at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:77)
    at android.app.Activity.dispatchActivityResult(Activity.java:6428)
    at android.app.ActivityThread.deliverResults(ActivityThread.java:3695)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742) 
    at android.app.ActivityThread.-wrap16(ActivityThread.java) 
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393) 
    at android.os.Handler.dispatchMessage(Handler.java:102) 
    at android.os.Looper.loop(Looper.java:148) 
    at android.app.ActivityThread.main(ActivityThread.java:5417) 
    at java.lang.reflect.Method.invoke(Native Method) 
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

**Comment by nateReiners** [comment]
still getting this in v0.26.10

**Comment by jindada** [comment]
+1
d: DOOGEE BL5000
version: 0.26.10

**Comment by rohit75** [comment]
Facing this issue on some devices. Any solution?

**Comment by waleedsarwar86** [comment]
Still getting the same issue

**Comment by agrass** [comment]
Me too, anyone already solved this??

**Comment by Johan-dutoit** [comment]
@waleedsarwar86 @agrass can you test this change locally: https://github.com/react-native-community/react-native-image-picker/pull/984 ?

i.e. make the change in your node_modules folder and let me know if it works.  If so, I'll happily merge the PR and release a new version.

**Comment by waleedsarwar86** [comment]
@Johan-dutoit Yup I have tested the change it works. So I think you can merge the PR.

**Comment by jordangrant** [comment]
@Johan-dutoit I also tested it and it works for my Huawei device

**Comment by sumeeti** [comment]
@Johan-dutoit Can you please merge #984 now that it's tested, thanks!

**Comment by Johan-dutoit** [comment]
Done.
