### ISSUE TITLE
Android5.1   ‘’Take photo‘‘ occur error and app crash

### ISSUE THREAD

**Issue by snyqm** [react-native-community/react-native-image-picker#612]
### Description

when i choose the “Take Photo” option，APP crash

### error code

java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.XmlResourceParser android.content.pm.ProviderInfo.loadXmlMetaData(android.content.pm.PackageManager, java.lang.String)' on a null object reference
	at android.support.v4.content.FileProvider.parsePathStrategy(FileProvider.java:560)
	at android.support.v4.content.FileProvider.getPathStrategy(FileProvider.java:534)
	at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:376)
	at com.imagepicker.utils.RealPathUtil.compatUriFromFile(RealPathUtil.java:31)
	at com.imagepicker.ImagePickerModule.launchCamera(ImagePickerModule.java:253)
	at com.imagepicker.ImagePickerModule.launchCamera(ImagePickerModule.java:203)
	at com.imagepicker.ImagePickerModule$2.onTakePhoto(ImagePickerModule.java:159)
	at com.imagepicker.utils.UI$1.onClick(UI.java:54)
	at android.support.v7.app.AlertController$AlertParams$3.onItemClick(AlertController.java:807)
	at android.widget.AdapterView.performItemClick(AdapterView.java:310)
	at android.widget.AbsListView.performItemClick(AbsListView.java:1233)
	at android.widget.AbsListView$PerformClick.run(AbsListView.java:3279)
	at android.widget.AbsListView$3.run(AbsListView.java:4235)
	at android.os.Handler.handleCallback(Handler.java:815)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loop(Looper.java:210)
	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:208)
	at java.lang.Thread.run(Thread.java:818)

**Comment by abdurrahmanekr** [comment]
remove these lines from AndroidManifest.xml file:
```xml
...
<provider
	android:name="android.support.v4.content.FileProvider"
	android:authorities="${applicationId}.fileprovider"
	android:grantUriPermissions="true"
	android:exported="false"
	tools:replace="android:authorities">
	<meta-data
	    android:name="android.support.FILE_PROVIDER_PATHS"
	    android:resource="@xml/file_paths"
	    tools:replace="android:resource"/>
</provider>
...
```

**Comment by iremlopsum** [comment]
@abdurrahmanekr I don't feel like this is the correct solution, instead there should be a subclass that extends the FileProvider, I can make a PR tomorrow to fix this issue

**Comment by kinandwair** [comment]
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-feature android:name="android.hardware.camera" android:required="false"/>
    <uses-feature android:name="android.hardware.camera.autofocus" />
add these line to AndroidManifest.xml ........ It worked for me

**Comment by zhenzhenjiang** [comment]
Now android 5.1, the camera permission is also opened, but a click ' 'Take photo', how do you solve this?

**Comment by snyqm** [comment]
distributionUrl=https\://services.gradle.org/distributions/gradle-2.14.1-all.zip  <- use gradle-2.14.1-all.zip
 classpath 'com.android.tools.build:gradle:2.2.+' // <- USE 2.2.+ version

fixed！！

**Comment by zhenzhenjiang** [comment]
Is there any other way to solve this problem? I am now using gradle-2.4-all.zip, using 1.2.3 version, and if I change it to your version, there will be more unexpected problems after compiling the program

**Comment by mbenjamin618** [comment]
@iremlopsum did you ever make that PR?

**Comment by iremlopsum** [comment]
@mbenjamin618 totally forgot, will do soon

**Comment by bozaigao** [comment]
@abdurrahmanekr you are right thank you very much!!!

**Comment by Gabriel-Bratescu** [comment]
Any news about this ? What is the correct way to proceed ?

**Comment by nu5rim3** [comment]
can any one help to write **file_paths.xml**
Image is saved here:   file:///data/user/0/com.mypet/cache/ReactNative-snapshot-image-327304329.jpg
```
<?xml version="1.0" encoding="utf-8"?>
<paths xmlns:android="http://schemas.android.com/apk/res/android">
    <files-path path="cache/" name="." />
</paths>
```
