### ISSUE TITLE
Real problem on react-native-navigation with react-native-image-picker  PLEASE help me!

### ISSUE THREAD

**Issue by mrxrinc** [react-native-community/react-native-image-picker#652]
I did all changes  suggested in here :
https://github.com/react-community/react-native-image-picker/pull/580/files

but still getting this red screen error and nothing works :(

here is the logcat error:

Exception in native call
java.lang.RuntimeException: Could not invoke ImagePickerManager.launchImageLibrary
at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:374)
at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:166)
at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
at android.os.Looper.loop(Looper.java:135)
at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.reflect.InvocationTargetException
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:363)
... 8 more
Caused by: java.lang.NoSuchMethodError: No virtual method requestPermissions([Ljava/lang/String;I)V in class Lcom/reactnativenavigation/controllers/NavigationActivity; or its super classes (declaration of 'com.reactnativenavigation.controllers.NavigationActivity' appears in /data/app/com.tahviler-2/base.apk)
at com.reactnativenavigation.controllers.NavigationActivity.requestPermissions(NavigationActivity.java:441)
at com.imagepicker.ImagePickerModule.permissionsCheck(ImagePickerModule.java:590)
at com.imagepicker.ImagePickerModule.launchImageLibrary(ImagePickerModule.java:298)
... 11 more

and this is screenshot:
![image](https://user-images.githubusercontent.com/10651894/28885264-82a8be04-77ca-11e7-85b5-d39a90f24afc.png)

I hope someone show a way to make these two modules work together, Im in real problem on this :(

### Additional Information

* React Native version: 0.46
* Platform: Android 5.1 and above
* Development Operating System: Windows
* Dev tools: [FILL THIS OUT: using Atom with nuclide

**Comment by cl1069573062** [comment]
l have a same problem.  Caused by: java.lang.NoSuchMethodError: No virtual method requestPermissions(

**Comment by LorandP** [comment]
I also experience this problem.

**Comment by luskin** [comment]
Thanks @LorandP - I tried your solution but unfortunately still crashes for me with: `java.lang.UnsupportedOperationException: NavigationActivity must implement OnImagePickerPermissionsCallback`

**Comment by codestersunion** [comment]
This PR should solve your issue @luskin https://github.com/react-community/react-native-image-picker/pull/761
