### ISSUE TITLE
No virtual method requestPermissions

### ISSUE THREAD

**Issue by cl1069573062** [react-native-community/react-native-image-picker#689]
### Description
when l use choose photo by camera  and my MainActivity is extend ReactActivity 
Caused by: java.lang.NoSuchMethodError: No virtual method requestPermissions([Ljava/lang/String;I)V in class Landroid/app/Activity; or its super classes (declaration of 'android.app.Activity' appears in /system/framework/framework.jar:classes2.dex)
    at com.facebook.react.ReactActivityDelegate.requestPermissions(ReactActivityDelegate.java:201)
    at com.facebook.react.ReactActivity.requestPermissions(ReactActivity.java:109)
    at com.imagepicker.ImagePickerModule.permissionsCheck(ImagePickerModule.java:581)
    at com.imagepicker.ImagePickerModule.launchImageLibrary(ImagePickerModule.java:297)
    at com.imagepicker.ImagePickerModule.launchImageLibrary(ImagePickerModule.java:283)
    at com.imagepicker.ImagePickerModule$2.onUseLibrary(ImagePickerModule.java:169)
    at com.imagepicker.utils.UI$1.onClick(UI.java:58)
    at android.support.v7.app.AlertController$AlertParams$3.onItemClick(AlertController.java:959)
    at android.widget.AdapterView.performItemClick(AdapterView.java:310)
    at android.widget.AbsListView.performItemClick(AbsListView.java:1188)
    at android.widget.AbsListView$PerformClick.run(AbsListView.java:3231)
    at android.widget.AbsListView$3.run(AbsListView.java:4165)
    at android.os.Handler.handleCallback(Handler.java:815)
    at android.os.Handler.dispatchMessage(Handler.java:104)
    at android.os.Looper.loop(Looper.java:194)
    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:194)
    at java.lang.Thread.run(Thread.java:818)

### Additional Information

* React Native version: 0.46.1
* Platform: Android
* Development Operating System: Android 5.1
* Dev tools: Android Studio version ： 2.2 ,  Android SDK version ： 22
  PhoneModel: HUAWEI(华为) MT7-TL10

**Comment by banli17** [comment]
are you solved this issue?i am the same

**Comment by yudhis8** [comment]
+1

**Comment by ab987cd** [comment]
Any solution ?

**Comment by j0nd0n7** [comment]
In my case I missed the addition of the
`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>`

Check [this](https://github.com/react-native-community/react-native-image-picker/blob/master/docs/Install.md) complete the installation

**Comment by seniordev0425** [comment]
> In my case I missed the addition of the
> `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>`
> 
> Check [this](https://github.com/react-native-community/react-native-image-picker/blob/master/docs/Install.md) complete the installation



> In my case I missed the addition of the
> `<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>`
> 
> Check [this](https://github.com/react-native-community/react-native-image-picker/blob/master/docs/Install.md) complete the installation

Thanks It works for me.
