### ISSUE TITLE
Android 8.1.0 WindowManager$BadTokenException:Unable to add window android.view.ViewRootImpl$W@f390edf -- permission denied for window type 2003

### ISSUE THREAD

**Issue by GavinSongBF** [react-native-community/react-native-image-picker#813]
FATAL EXCEPTION: main
                                                             Process: com.example, PID: 12265
                                                             android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@f390edf -- permission denied for window type 2003
                                                                 at android.view.ViewRootImpl.setView(ViewRootImpl.java:789)
                                                                 at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:356)
                                                                 at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
                                                                 at android.app.Dialog.show(Dialog.java:330)
                                                                 at com.facebook.react.devsupport.DevSupportManagerImpl.showProgressDialog(DevSupportManagerImpl.java:762)
                                                                 at com.facebook.react.devsupport.DevSupportManagerImpl.reloadJSFromServer(DevSupportManagerImpl.java:767)
                                                                 at com.facebook.react.devsupport.DevSupportManagerImpl.handleReloadJS(DevSupportManagerImpl.java:658)
                                                                 at com.facebook.react.XReactInstanceManagerImpl$3$1.run(XReactInstanceManagerImpl.java:412)
                                                                 at android.os.Handler.handleCallback(Handler.java:790)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                 at android.os.Looper.loop(Looper.java:164)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:6494)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by GavinSongBF** [comment]
buildToolsVersion 由“27”降为'26.0.2'运行正常

**Comment by hzburki** [comment]
Is there a way around this ? I don't want to upgrade to RN version because it starts breaking everything else. I'm working with RN 0.47.2.

**Comment by askarhu** [comment]
I ran into this issue as well and not in a situation to take on a full upgrade. Anyone resolution to this? Looks like some sort of a special permission gate we have to open up with Android 8+

**Comment by hzburki** [comment]
I initially tried upgrading RN, but upgrading it to even 0.48 started giving my problems with packages and styling. So I decided to downgrade the `targetSdkVersion` from 27 to 25. Everything works fine now :)

**Comment by lord22shark** [comment]
Hey @hzburki! I am facing the same problem. Have an app wrote with RN 0.40 and many other dependencies. I was building to targetSdkVersion 22. But now... to upload the APK to Google Play its demands targetSdkVersion 26. Any ideas? Or should I reestructure (create a new RN, add all dependencies [one by one] and than import the existing code)??? Quite desperate here! :-D

**Comment by hzburki** [comment]
Hi @lord22shark, first of all is it absolutely necessary to upgrade to sdk 26? Why not try version 25. 

Alternately you can also upgrade your RN version. So that it matches the SDK you want. There are medium articles and even some github repos to help you do that.

**Comment by javi10823** [comment]
I have the same problem, any solution?

**Comment by reynaldi-lorenzo** [comment]
use android product flavors feature and set for your debug flavor to use target sdk as mentioned by @hzburki above

> I initially tried upgrading RN, but upgrading it to even 0.48 started giving my problems with packages and styling. So I decided to downgrade the `targetSdkVersion` from 27 to 25. Everything works fine now :)

**Comment by devSumitKumar** [comment]
I am facing the same issue on the latest react native version(0.61.5). Please help.
