### ISSUE TITLE
Couldn't get file path for photo

### ISSUE THREAD

**Issue by Darkhorse-Fraternity** [react-native-community/react-native-image-picker#874]
* Please read the following carefully before opening a new issue.
Your issue may be closed if it does not provide the information required by this template.

Environment:
  OS: macOS Sierra 10.12.6
  Node: 9.1.0
  Yarn: 1.3.2
  npm: 6.1.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.1 AI-173.4720617

Packages: (wanted => installed)
  react: ^16.4.1 => 16.4.1
  react-native: ^0.55.4 => 0.55.4

"react-native-image-picker": "^0.26.10"

when i took the photo ,it crash:
Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media/28756 from pid=1655, uid=10152 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()

when i Taking pictures：
ImagePicker Error:  Couldn't get file path for photo

my permission:
<uses-permission android:name="android.permission.CAMERA"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />

I set up，
`<provider
            android:name="android.support.v4.content.FileProvider"
            android:authorities="${applicationId}.provider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                tools:replace="android:resource"
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/provider_image_picker_paths" />
 </provider>`

but No role。

**Comment by yuvaraj119** [comment]
How did you fix this I am getting the same error { error: 'Couldn\'t get file path for photo' }

"LOG"
07-13 15:54:43.269 24188-24227/com.wishbook.catalogone.sales W/System.err: java.lang.IllegalArgumentException: Failed to find configured root that contains /storage/emulated/0/Pictures/image-e1e5d11b-522a-4520-abc6-05b060462866.jpg
        at android.support.v4.content.FileProvider$SimplePathStrategy.getUriForFile(FileProvider.java:711)
        at android.support.v4.content.FileProvider.getUriForFile(FileProvider.java:400)
        at com.imagepicker.utils.RealPathUtil.compatUriFromFile(RealPathUtil.java:31)
        at com.imagepicker.ImagePickerModule.launchCamera(ImagePickerModule.java:258)
        at com.imagepicker.ImagePickerModule.launchCamera(ImagePickerModule.java:207)
        at com.imagepicker.ImagePickerModule$2.onTakePhoto(ImagePickerModule.java:163)
        at com.imagepicker.utils.UI$1.onClick(UI.java:54)
        at android.support.v7.app.AlertController$AlertParams$3.onItemClick(AlertController.java:959)
        at android.widget.AdapterView.performItemClick(AdapterView.java:334)
        at android.widget.AbsListView.performItemClick(AbsListView.java:1531)
07-13 15:54:43.279 24188-24227/com.wishbook.catalogone.sales W/System.err:     at android.widget.AbsListView$PerformClick.run(AbsListView.java:3664)
        at android.widget.AbsListView.onTouchUp(AbsListView.java:5600)
        at android.widget.AbsListView.onTouchEvent(AbsListView.java:5366)
        at android.view.View.dispatchTouchEvent(View.java:8962)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2698)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2410)
        at android.widget.AbsListView.dispatchTouchEvent(AbsListView.java:5303)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2709)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2425)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2559)
        at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1767)
        at android.app.Dialog.dispatchTouchEvent(Dialog.java:863)
        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:67)
        at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2520)
        at android.view.View.dispatchPointerEvent(View.java:9167)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4706)
07-13 15:54:43.289 24188-24227/com.wishbook.catalogone.sales W/System.err:     at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4544)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4068)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4121)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4087)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4201)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4095)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4258)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4068)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4121)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4087)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4095)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4068)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6564)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6454)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6425)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:6654)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
        at android.os.MessageQueue.nativePollOnce(Native Method)
        at android.os.MessageQueue.next(MessageQueue.java:143)
        at android.os.Looper.loop(Looper.java:130)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
        at java.lang.Thread.run(Thread.java:818)
07-13 15:54:43.289 24188-24226/com.wishbook.catalogone.sales I/ReactNativeJS: 'Response = ', { error: 'Couldn\'t get file path for photo' }
    'ImagePicker Error: ', 'Couldn\'t get file path for photo'
07-13 15:54:43.339 24188-24227/com.wishbook.catalogone.sales W/InputEventReceiver: Attempted to finish an input event but the input event receiver has already been disposed.
07-13 15:54:43.339 24188-24227/com.wishbook.catalogone.sales E/ViewRootImpl: sendUserActionEvent() mView == null

**Comment by monicse09ku** [comment]
Is it solved? How to solve it?

**Comment by SalviShahzad** [comment]
@zirtuedeveloper where to get this FilePath.xml file?

**Comment by jose2007kj** [comment]
the following answer solved my issue https://github.com/react-native-community/react-native-image-picker/issues/928#issuecomment-438526153

**Comment by williamgoodhew** [comment]
I am still having this issue.

I m on react-native v0.61.5 and there is not filepath.xml file.

Does anyone have any other suggestions?

I am only getting this error with Android.

Here is my `AndroidManifest.xml`

```
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
  package="com.athalens">

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>

</manifest>
```

Here is my react-native code

```
ImagePicker.launchCamera(options, response => {

      if (response.didCancel) {
        console.log('User cancelled image picker');
      } else if (response.error) {
        console.log('ImagePicker Error: ', response.error);
      } else if (response.customButton) {
        console.log('User tapped custom button: ', response.customButton);
      } else {
        const uri = response.uri;
        Actions.uploadSelfieProgress();
        this.props.setSelfie(uri, uid);
      }
    });
```

I am getting the following error.

`ImagePicker Error:  Couldn't get file path for photo`

I have read elsewhere that React-native-share can cause the filepath error. I have RN-Share installed.

**Comment by edilsonlm217** [comment]
I just got a solution for this problem.
When installing react-native-image-picker you have to add bellow lines to android/app/src/debug/AndroidManifest.xml in order to get permission to access device's camera and storage.

<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
<uses-permission android:name="android.permission.CAMERA"/>

Don't know why but for some reason when you call ImagePicker.launchCamera by app it doesn't ask for sotrage permission. That's why it can't get file path for photo.

To make it run you got to allow storage permisson manually in your device or emulator.

In case you don't know how to do that follow the steps described in the link: https://phandroid.com/2019/07/18/how-to-change-app-permissions-android-m/

**Comment by PragyanD33p** [comment]
@edilsonlm217 It asks for permission. Thats not the problem. The problem is that only the camera for photo is not opening. However the camera for video is opening fine. When opening camera for photo it gives error  "ImagePicker Error:  Couldn't get file path for photo".

**Comment by ZenBoat** [comment]
I have the same issue: the launchCamera doesn't ask for file permissions, even though it needs it.

**Comment by AmrAlmagic** [comment]
@wcandillon @edilsonlm217  @PragyanD33p @ZenBoat 

I also faced this issue that happened if you select the first time take photo not choose from library so I think related to storage android permissions.
 according to [android permission](https://facebook.github.io/react-native/docs/permissionsandroid#requestmultiple) i made 

```
const checkAllPermissions = async () => {
        try {
            await PermissionsAndroid.requestMultiple
            ([PermissionsAndroid.PERMISSIONS.CAMERA, PermissionsAndroid.PERMISSIONS.READ_EXTERNAL_STORAGE, PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE]);
            if ((await PermissionsAndroid.check('android.permission.CAMERA')) &&
                (await PermissionsAndroid.check('android.permission.CAMERA')) &&
                (await PermissionsAndroid.check('android.permission.CAMERA'))) {
                console.log('You can use the camera');
                return true;
            } else {
                console.log('all permissions denied');
                return false;
            }
        } catch (err) {
            console.warn(err);
        }
    };
```
and call this function before use ImagePicker.
and works well now from the first time select take Photo.

**Comment by inanBekir** [comment]
> @wcandillon @edilsonlm217 @PragyanD33p @ZenBoat
> 
> I also faced this issue that happened if you select the first time take photo not choose from library so I think related to storage android permissions.
> according to [android permission](https://facebook.github.io/react-native/docs/permissionsandroid#requestmultiple) i made
> 
> ```
> const checkAllPermissions = async () => {
>         try {
>             await PermissionsAndroid.requestMultiple
>             ([PermissionsAndroid.PERMISSIONS.CAMERA, PermissionsAndroid.PERMISSIONS.READ_EXTERNAL_STORAGE, PermissionsAndroid.PERMISSIONS.WRITE_EXTERNAL_STORAGE]);
>             if ((await PermissionsAndroid.check('android.permission.CAMERA')) &&
>                 (await PermissionsAndroid.check('android.permission.CAMERA')) &&
>                 (await PermissionsAndroid.check('android.permission.CAMERA'))) {
>                 console.log('You can use the camera');
>                 return true;
>             } else {
>                 console.log('all permissions denied');
>                 return false;
>             }
>         } catch (err) {
>             console.warn(err);
>         }
>     };
> ```
> 
> and call this function before use ImagePicker.
> and works well now from the first time select take Photo.

this is worked really thank you so much i search 3 days this solution

**Comment by hautran96** [comment]
it not working with android 10

Environment:
  "react-native": "0.61.5",

**Comment by Rutvik17** [comment]
> it not working with android 10
> 
> Environment:
> "react-native": "0.61.5",

I am having the same issue with android 10 and i am asking for all the permissions

**Comment by Rutvik17** [comment]
> it not working with android 10
> 
> Environment:
> "react-native": "0.61.5",

Please check this comment https://github.com/react-native-community/react-native-image-picker/issues/928#issuecomment-621283885 
This solved my issue on android 10

**Comment by rishiankush** [comment]
I was able to fix it by adding `android:requestLegacyExternalStorage="true"` to application tag in AndroidManifest.xml file

**Comment by Harkindey** [comment]
@rishiankush THIS IS IT.
Thank YOU.

**Comment by pujieko** [comment]
> I was able to fix it by adding `android:requestLegacyExternalStorage="true"` to application tag in AndroidManifest.xml file

Im done with this... u da' real mvp man :D

**Comment by hautran96** [comment]
@rishiankush 
thank you,  it work for me

**Comment by desai-hardik** [comment]
As on 30-10-20 this issue only happens in Android Version 10 (I've only tested in emulator) and this can be solve by  

adding `android:requestLegacyExternalStorage="true"` to application tag in AndroidManifest.xml file as per answer given by @rishiankush
