### ISSUE TITLE
In android 4.x simulator, com.imagepicker.FileProvider

### ISSUE THREAD

**Issue by SurpassRabbit** [react-native-community/react-native-image-picker#924]
### Description

android simulator  4.x version， An error com.imagepicker.FileProvider

### How to repeat issue and example

react-native 0.55.4
react-native-image-picker ^0.26.10

### Additional Information

```
E/AndroidRuntime: FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to get provider com.imagepicker.FileProvider: java.lang.ClassNotFoundException: com.imagepicker.FileProvider
        at android.app.ActivityThread.installProvider(ActivityThread.java:4563)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4190)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4132)
        at android.app.ActivityThread.access$1300(ActivityThread.java:130)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1255)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:137)
        at android.app.ActivityThread.main(ActivityThread.java:4745)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:511)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.ClassNotFoundException: com.imagepicker.FileProvider
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:61)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
        at android.app.ActivityThread.installProvider(ActivityThread.java:4548)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:4190) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4132) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:130) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1255) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:137) 
        at android.app.ActivityThread.main(ActivityThread.java:4745) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:511) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553) 
        at dalvik.system.NativeStart.main(Native Method) 
```

* React Native version:  0.55.4
* Platform: Android
* Development Operating System:  Mac
* Dev tools:  Android studio 3.1.3

**Comment by OrangeFlavoredColdCoffee** [comment]
same error 
![image](https://user-images.githubusercontent.com/15223345/49992373-d9ef2e00-ffbe-11e8-8e5c-79cea147619c.png)

**Comment by OrangeFlavoredColdCoffee** [comment]
![image](https://user-images.githubusercontent.com/15223345/49992465-220e5080-ffbf-11e8-9a18-3a9020e8146a.png)
same error

**Comment by Jeijie** [comment]
any update for this?, I have same issue on OPPO R7s,Android 4.4.4

**Comment by SurpassRabbit** [comment]
@Jeijie RN 版本多少？

**Comment by JB-CHAUVIN** [comment]
Same issue for me... any fix ?
