### ISSUE TITLE
[Android] Failed to pick an image. 

### ISSUE THREAD

**Issue by denny1314** [react-native-community/react-native-image-picker#995]
### Description

We are using MobileIron Android-AppConnect to wrap the app. The app crashies upon finishing to pick an image.
`java.lang.IllegalArgumentException: column '_data' does not exist. Available columns: []`

### Cause
File: RealPathUtil.java
Method: getRealPathFromURI(..)
`public static @Nullable String getRealPathFromURI(@NonNull final Context context,
													  @NonNull final Uri uri)
 {
...
String _data = getDataColumn(context, uri, null, null);
...
}`
The **_data** column is not available at FileProvider Uri. And it is not guarentee to get real path from a Uri. It may not even point to a file. If you absolutely need a local copy of the file, you are going to need to open the **InputStream** copy the contents to a local file that you know the path to and then go from there.

### Solution

provide a pull request with a fix.

### Additional Information

* React Native version: 0.27.0
* Platform: Android
* Development Operating System: MacOS

**Comment by sanshao** [comment]
The same problem:
`
java.lang.IllegalArgumentException: column '_data' does not exist. Available columns: []
    at android.app.ActivityThread.deliverResults(ActivityThread.java:4323)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:4367)
    at android.app.ActivityThread.-wrap19(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1665)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6602)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:453)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821)
Caused by: java.lang.IllegalArgumentException: column '_data' does not exist. Available columns: []
    at android.database.AbstractCursor.getColumnIndexOrThrow(AbstractCursor.java:340)
    at android.database.CursorWrapper.getColumnIndexOrThrow(CursorWrapper.java:87)
    at com.imagepicker.O00000o0.O00000o.O000000o(RealPathUtil.java:135)
    at com.imagepicker.O00000o0.O00000o.O000000o(RealPathUtil.java:102)
    at com.imagepicker.ImagePickerModule.getRealPathFromURI(ImagePickerModule.java:636)
    at com.imagepicker.ImagePickerModule.onActivityResult(ImagePickerModule.java:419)
    at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:253)
    at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:692)
    at com.reactnativenavigation.O00000o0.O0000OOo.O000000o(NavigationReactGateway.java:105)
    at com.reactnativenavigation.controllers.NavigationActivity.onActivityResult(NavigationActivity.java:232)
    at android.app.Activity.dispatchActivityResult(Activity.java:7304)
    at android.app.ActivityThread.deliverResults(ActivityThread.java:4319)
    ... 9 more
java.lang.IllegalArgumentException: column '_data' does not exist. Available columns: []
    at android.database.AbstractCursor.getColumnIndexOrThrow(AbstractCursor.java:340)
    at android.database.CursorWrapper.getColumnIndexOrThrow(CursorWrapper.java:87)
    at com.imagepicker.O00000o0.O00000o.O000000o(RealPathUtil.java:135)
    at com.imagepicker.O00000o0.O00000o.O000000o(RealPathUtil.java:102)
    at com.imagepicker.ImagePickerModule.getRealPathFromURI(ImagePickerModule.java:636)
    at com.imagepicker.ImagePickerModule.onActivityResult(ImagePickerModule.java:419)
    at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:253)
    at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:692)
    at com.reactnativenavigation.O00000o0.O0000OOo.O000000o(NavigationReactGateway.java:105)
    at com.reactnativenavigation.controllers.NavigationActivity.onActivityResult(NavigationActivity.java:232)
    at android.app.Activity.dispatchActivityResult(Activity.java:7304)
    at android.app.ActivityThread.deliverResults(ActivityThread.java:4319)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:4367)
    at android.app.ActivityThread.-wrap19(Unknown Source:0)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1665)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:164)
    at android.app.ActivityThread.main(ActivityThread.java:6602)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:453)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:821)
`

Android version: 8.1.0
Device Type: 1809-A01
Brand: 360 Phone N7 Pro

**Comment by dann1609** [comment]
I have this problem trying to copy a file captured with a camera. If I pick from the gallery it doesn't happen.

**Comment by CQBOBOZHU** [comment]
I get the same problem
![image](https://user-images.githubusercontent.com/20177774/69694969-9af5b200-1115-11ea-998f-9fd1fb17fefa.png)

![image](https://user-images.githubusercontent.com/20177774/69695012-be206180-1115-11ea-9b54-4c655437e915.png)

**Comment by CQBOBOZHU** [comment]
my device info 
![image](https://user-images.githubusercontent.com/20177774/69695060-ec05a600-1115-11ea-82fc-18cd13ed11d2.png)

**Comment by ChrisEelmaa** [comment]
Same problem here.

Android 10, Pixel 3a

As far as I can tell, don't think it is particularily related to the model / Android version.

**Comment by laurent22** [comment]
Same problem here: https://github.com/laurent22/joplin/issues/3981
